name: sample
description: A new Flutter project.

publish_to: "none"

version: 10.0.1+423

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  firebase_core: ^1.24.0
  firebase_storage:
    path: ../flutterfire/packages/firebase_storage/firebase_storage
  flutter:
    sdk: flutter
  flutter_isolate: ^2.0.3
  path_provider: ^2.0.11
dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/dell.jpg
